# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Adr < Formula
  desc ""
  homepage "https://github.com/herrmannplatz/adr"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/herrmannplatz/adr/releases/download/v0.0.2/adr_Darwin_x86_64.tar.gz"
      sha256 "6da7b63506826adc43e425b1ac64d327dfa8595095083c7771f0caf60e9297a4"

      def install
        bin.install "adr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/herrmannplatz/adr/releases/download/v0.0.2/adr_Darwin_arm64.tar.gz"
      sha256 "42113dd14ccc0d437682f3c8767e5235d26c844affe5f49021931af5468b7956"

      def install
        bin.install "adr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/herrmannplatz/adr/releases/download/v0.0.2/adr_Linux_x86_64.tar.gz"
        sha256 "1f6476b2f2ee9fe4724b7e0b55b2d355094d4cc967a62393fadcc8278eb4a531"

        def install
          bin.install "adr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/herrmannplatz/adr/releases/download/v0.0.2/adr_Linux_arm64.tar.gz"
        sha256 "d34a62d1f6bcc78c5f0946fffaa7b55aa6192f20a6c6e3fb8654831d7163e93f"

        def install
          bin.install "adr"
        end
      end
    end
  end
end
