# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Adr < Formula
  desc ""
  homepage "https://github.com/herrmannplatz/adr"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/herrmannplatz/adr/releases/download/v0.0.1/adr_Darwin_x86_64.tar.gz"
      sha256 "3cf8594ce98fe89c357dd04a8b01711e8a4a0a7324d8959a2b116682de6638de"

      def install
        bin.install "adr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/herrmannplatz/adr/releases/download/v0.0.1/adr_Darwin_arm64.tar.gz"
      sha256 "d8886fa70a7e8924fbfebd286ddbb3d34c3d03baef68054bb1ed67e73c04d2f0"

      def install
        bin.install "adr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/herrmannplatz/adr/releases/download/v0.0.1/adr_Linux_x86_64.tar.gz"
        sha256 "fe33e0e3d9f47d46d46a62126cbd2296dcd2121898080d74783d23a60c47f002"

        def install
          bin.install "adr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/herrmannplatz/adr/releases/download/v0.0.1/adr_Linux_arm64.tar.gz"
        sha256 "6fe6d15ec93bb6d2f38894e10c60493a6b59290707598e4834aa3e20658f696e"

        def install
          bin.install "adr"
        end
      end
    end
  end
end
